pipeline {
    agent {
        label 'master'
    }
    stages {
        stage("Log Analysis") {
            steps {
               
                    // Run journalctl and save the output to log.txt
                    sh "sudo journalctl | grep 'error' | tail -20 > log.txt"

                    // Run sgpt to check the logs and generate Document.txt
                    sh "cat log.txt | sgpt \"analyse logs and generate linux commands with explanation to fix issues\" > Suggestions.txt"
                    sh "cat log.txt | sgpt -s \"analyse logs and generate linux commands to fix issues\" > Document.txt"
                    sh "echo \"#!/bin/bash\">script.sh"
                    sh "cat Document.txt>>script.sh"
                    sh "chmod +x script.sh"
                    sh "./script.sh"
                
            }
            post {
                success {
                    // Archive the Document.txt for reference
                    archiveArtifacts artifacts: 'Suggestions.txt, Document.txt, script.sh'
                }
            }
        }

        

        // stage("Sending Email") {
        //     steps {
        //         script {
        //             // Send an email with the generated PDF attachment
        //             sh '''sendemail  -f Jenkins@PE.com -t abhishek.velichala@tcs.com -cc ramteja.vasupari@tcs.com, pavan.daggupati@tcs.com -u "Log Analysis" -m "Hi Team, Please find the attached Suggestions document generated by ChatGPT for the given logs.
        //             From: Jenkins" -s smtp.gmail.com:587 -a output.pdf -o tls=yes -xu aalucky555@gmail.com -xp guhguhzykgtgqddd'''
        //         }
        //     }
        // }
    }
}
