---
- name: Deploy Jupyter-notebook Docker container
  hosts: all
  become: yes
  tasks:
    - name: Installing python3
      apt:
        name: python3-pip
        state: present

    - name: Installing Keras package using pip
      ansible.builtin.pip:
        name: keras
