---
- name: Deploy code-server Docker container
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Installing python3
      apt:
        name: python3-pip
        state: present
    - name: Installing docker package using pip
      ansible.builtin.pip:
        name: docker

    - name: Start code-server Docker container
      community.docker.docker_container:
        name: code-server1
        image: lscr.io/linuxserver/code-server:latest
        detach: yes
        env:
          TZ: "Etc/UTC"
        ports:
          - "3000:8443"
        volumes:
          - "/home/ubuntu/config:/config"
        restart_policy: unless-stopped
